---

workspace:
  base: /hass

pipeline:
  - python_3.5:
      image: python:3.5-stretch
      commands:
        - mv mock_secrets.yaml secrets.yaml
        - pip install homeassistant
        - hass -c . --script check_config
    python_3.6:
      image: python:3.6-stretch
      commands:
        - mv mock_secrets.yaml secrets.yaml
        - pip install homeassistant
        - hass -c . --script check_config
  - ssh:
      image: appleboy/drone-ssh
      host: 192.168.1.50
      port: 22
      username: root
      secrets: [ ssh_key ]
      script:
        - cd /home/trek/hassio/homeassistant
        - git pull
        - docker restart homeassistant
