---
workspace:
  bass: /hass

kind: pipeline
name: default

steps:
  - name: Test
    image: python:3.5
    commands:
      - mv mock_secrets.yaml secrets.yaml
      - pip install homeassistant
      - hass -c . --script check_config

  - name: Update Hassio
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.50
      username:
        from_secret: username
      ssh_key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /home/trek/hassio/homeassistant
        - git pull
        - docker restart homeassistant


sudo docker run --volume=/var/run/docker.sock:/var/run/docker.sock --volume=/var/lib/drone:/data --env=DRONE_USER_CREATE=username:finish06,admin:true --env=DRONE_GITHUB_SERVER=https://github.com --env=DRONE_GITHUB_CLIENT_ID=a8e41ddb60e7825fb6fe --env=DRONE_GITHUB_CLIENT_SECRET=af26ae5263517f7e671aae09691745a9b6f29e54 --env=DRONE_RUNNER_CAPACITY=2 --env=DRONE_SERVER_HOST=drone.calebdunn.tech --env=DRONE_SERVER_PROTO=https --env=DRONE_TLS_AUTOCERT=true --publish=80:80 --publish=443:443 --restart=always --detach=true --name=drone drone/drone:1.0.0-rc.6
