---
workspace:
  bass: /hass

kind: pipeline
name: default

steps:
  - name: Test
    image: python:3.5
    commands:
      - mv mock_secrets.yaml secrets.yaml
      - pip install homeassistant
      - hass -c . --script check_config

  - name: Update Hassio
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.50
      username:
        from_secret: username
      ssh_key:
        from_secret: ssh_key_pub
      port: 22
      script:
        - cd /home/trek/hassio/homeassistant
        - git pull
        - docker restart homeassistant
