---

kind: pipeline
name: default

steps:
  - name: Test
    image: python:3.5
    commands:
      - mv mock_secrets.yaml secrets.yaml
      - pip install homeassistant
      - hass -c . --script check_config

  - name: Update Hassio
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.50
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /usr/share/hassio/homeassistant
        - git pull
        - docker restart homeassistant
