---

kind: pipeline
name: default

steps:
  - name: Test
    image: ubuntu:latest
    commands:
      - mv mock_secrets.yaml secrets.yaml
      - cp -r . /config/
      - rm -rf /config/components/device_tracker.yaml
      - ls /config
      - apt-get update
      - apt-get install -y python3-dev pkg-config python3-pip
      - apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
      - pip3 install homeassistant
      - hass -c /config --script check_config

  - name: Update Hassio
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.50
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /usr/share/hassio/homeassistant
        - git pull
        - docker restart homeassistant
