---
workspace:
  bass: /hass

kind: pipeline
name: default

steps:
  - name: Test
    image: python:3.5
    commands:
      - mv mock_secrets.yaml secrets.yaml
      - pip install homeassistant
      - hass -c . --script check_config
  - name: Update
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.50
      port: 22
      username: root
      secrets: [ ssh_key ]
      script:
        - cd /home/trek/hassio/homeassistant
        - git pull
        - docker restart homeassistant
