---

workspace:
  base: /hass

pipeline:
  build:
    image: python:3
    commands:
      - mv travis_secrets.yaml secrets.yaml
      - pip install homeassistant
      - hass -c . --script check_config
  ssh:
    image: appleboy/drone-ssh
    host: 192.168.1.50
    port: 22
    username: root
    secrets: [ ssh_key ]
    script:
      - cd /home/trek/hassio/homeassistant
      - git pull
