homeassistant:
  # Name of the location where Home Assistant is running
  # name: Dunn's Home Assistant
  # Location required to calculate the time the sun rises and sets
  # latitude: !secret latitude_location
  # longitude: !secret longitude_location
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 192
  # metric for Metric, imperial for Imperial
  # unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/Chicago
  # Customization file
  customize: !include ui/customize.yaml
  # Trusted Networks
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.8.0.0/16
        - !secret my_ip
    - type: homeassistant

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.26
    - 192.168.1.41
    - 192.168.1.42
    - 192.168.1.43
    - !secret my_ip
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22
  ip_ban_enabled: true
  login_attempts_threshold: 15

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yamaha

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Support Android/ iOS mobile apps
mobile_app:

# Logging
logger:
  default: error
  logs:
    homeassistant.components.myq: critical

# Enables a map showing the location of tracked devices
map:
  hours_to_show: 24

recorder:
  db_url: !secret db_url

# System health for APIs
system_health:

# Track the sun
sun:

# Components
automation: !include automations.yaml
binary_sensor: !include components/binary_sensors.yaml
camera: !include components/camera.yaml
climate: !include components/climate.yaml
cloud: !include components/cloud.yaml
device_tracker: !include components/device_tracker.yaml
downloader:
  download_dir: /config/www/snaps/
energy:
group: !include_dir_merge_named ui/groups/
homekit: !include components/homekit.yaml
ifttt: !include components/ifttt.yaml
image_processing: !include components/image_processing.yaml
influxdb: !include components/influxdb.yaml
input_number: !include components/input_number.yaml
input_select: !include components/input_select.yaml
input_boolean:
isy994: !include components/isy994.yaml
light: !include components/lights.yaml
media_player: !include components/media_players.yaml
media_source:
mqtt: !include components/mqtt.yaml
my:
notify: !include components/notify.yaml
nzbget: !include components/nzbget.yaml
script: !include scripts.yaml
sensor: !include components/sensors.yaml
speedtestdotnet: !include components/speedtest.yaml
spotify: !include components/spotify.yaml
stream:
switch: !include components/switches.yaml
template: !include components/template.yaml
tts: !include components/tts.yaml
weather: !include components/weather.yaml

# Retired configs
# cover: !include components/cover.yaml
# ecobee: !include components/ecobee.yaml
# telegram_bot: !include components/telegram_bot.yaml
# intent_script: !include_dir_merge_named components/intents
# unifi: !include components/unifi.yaml
