homeassistant:
  name: Overview
  latitude: !secret latitude_location
  longitude: !secret longitude_location
  elevation: 192
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize/customize.yaml
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    group.main_living_temps:
      state_card_mode: badges
    group.room_temps_1:
      state_card_mode: badges
    group.room_temps_2:
      state_card_mode: badges
    group.motion_badges:
      state_card_mode: badges


config:
customizer:
   custom_ui: debug
discovery:
  ignore:
    - philips_hue
    - samsung_tv
    - sonos
    - yamaha
    - harmony
frontend:
  themes: !include_dir_merge_named customize/themes/
history:
http:
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.11
    - 192.168.1.181
    - 10.8.0.0/16
  ip_ban_enabled: true
  login_attempts_threshold: 3
ios:
logbook:
logger:
  default: error
  logs:
    homeassistant.components.cover: critical
recorder:
sun:
updater:

##############
# Components #
##############
automation: !include automations.yaml
binary_sensor: !include components/binary_sensors.yaml
camera: !include components/camera.yaml
climate: !include components/climate.yaml
cover: !include components/cover.yaml
device_tracker: !include components/device_tracker.yaml
dialogflow:
ecobee: !include components/ecobee.yaml
google_assistant: !include components/google_assistant.yaml
group: !include components/group.yaml
hue: !include components/hue.yaml
ifttt:
  key: !secret ifttt_key
#influxdb: !include components/influxdb.yaml
input_boolean: !include components/input_boolean.yaml
input_select: !include components/input_select.yaml
intent_script: !include_dir_merge_named components/intents
isy994: !include components/isy994.yaml
light: !include components/lights.yaml
lock: !include components/locks.yaml
media_player: !include components/media_players.yaml
mqtt: !include components/mqtt.yaml
notify: !include components/notify.yaml
#remote: !include components/remotes.yaml
script: !include components/scripts.yaml
sensor: !include components/sensors.yaml
shell_command: !include_dir_merge_named components/shell_commands/
switch: !include components/switches.yaml
tts:
  - platform: google
    language: 'en'
