homeassistant:
  # Name of the location where Home Assistant is running
  name: Overview
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_location
  longitude: !secret longitude_location
  # Impacts weather/sunrise data
  elevation: 192
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customize
  customize: !include extraconfig/customize.yaml

# Enables configuration UI
config:

# Enables the frontend
frontend:
  themes:
    happy:
      primary-color: green

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.11
    - 192.168.1.181
    - 10.8.0.0/16
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
    - samsung_tv
    - sonos
    - yamaha
    - harmony

# Enables support for tracking state changes over time.
history:

# Enables support for database purging
recorder:
  purge_days: 7

# View all events in a logbook
logbook:

#Log setting
logger:
  default: error

# Track the sun
sun:

##############
# Components #
##############
automation: !include automations.yaml
binary_sensor: !include extraconfig/binary_sensors.yaml
climate: !include extraconfig/climate.yaml
cover: !include extraconfig/cover.yaml
device_tracker: !include extraconfig/device_tracker.yaml
ecobee: !include extraconfig/ecobee.yaml
emulated_hue: !include extraconfig/emulated_hue.yaml
group: !include extraconfig/group.yaml
influxdb: !include extraconfig/influxdb.yaml
input_boolean: !include extraconfig/input_boolean.yaml
input_select: !include extraconfig/input_select.yaml
ios:
isy994: !include extraconfig/isy994.yaml
light: !include extraconfig/lights.yaml
lock: !include extraconfig/locks.yaml
media_player: !include extraconfig/media_players.yaml
mqtt: !include extraconfig/mqtt.yaml
notify: !include extraconfig/notify.yaml
remote: !include extraconfig/remotes.yaml
sensor: !include extraconfig/sensors.yaml
shell_command: !include_dir_merge_named extraconfig/shell_commands/
switch: !include extraconfig/switches.yaml
