homeassistant:
  name: Overview
  latitude: !secret latitude_location
  longitude: !secret longitude_location
  elevation: 192
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include extraconfig/customize.yaml

config:
discovery:
  ignore:
    - philips_hue
    - samsung_tv
    - sonos
    - yamaha
frontend:
  themes:
    happy:
      primary-color: green
history:
http:
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.11
    - 192.168.1.181
    - 10.8.0.0/16
  ip_ban_enabled: true
  login_attempts_threshold: 3
ios:
logbook:
logger:
  default: error
  logs:
    homeassistant.components.cover: critical
recorder:
  purge_days: 7
sun:
updater:

##############
# Components #
##############
automation: !include automations.yaml
binary_sensor: !include extraconfig/binary_sensors.yaml
climate: !include extraconfig/climate.yaml
cover: !include extraconfig/cover.yaml
device_tracker: !include extraconfig/device_tracker.yaml
ecobee: !include extraconfig/ecobee.yaml
emulated_hue: !include extraconfig/emulated_hue.yaml
group: !include extraconfig/group.yaml
influxdb: !include extraconfig/influxdb.yaml
input_boolean: !include extraconfig/input_boolean.yaml
input_select: !include extraconfig/input_select.yaml
isy994: !include extraconfig/isy994.yaml
light: !include extraconfig/lights.yaml
lock: !include extraconfig/locks.yaml
media_player: !include extraconfig/media_players.yaml
mqtt: !include extraconfig/mqtt.yaml
notify: !include extraconfig/notify.yaml
remote: !include extraconfig/remotes.yaml
sensor: !include extraconfig/sensors.yaml
shell_command: !include_dir_merge_named extraconfig/shell_commands/
switch: !include extraconfig/switches.yaml
