homeassistant:
  # Name of the location where Home Assistant is running
  name: Dunn's Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_location
  longitude: !secret longitude_location
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 192
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include ui/customize.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named ui/themes/

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  base_url: !secret base_url
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.11
    - 192.168.1.126
    - 10.8.0.0/16
  ip_ban_enabled: true
  login_attempts_threshold: 3


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv
    - yamaha
    - harmony

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Logging
logger:

# Enables a map showing the location of tracked devices
map:

recorder:
  purge_keep_days: 3
  purge_interval: 1

# Track the sun
sun:


# Components
automation: !include_dir_list automations/
binary_sensor: !include components/binary_sensors.yaml
camera: !include components/camera.yaml
climate: !include components/climate.yaml
cloud: !include components/cloud.yaml
cover: !include components/cover.yaml
device_tracker: !include components/device_tracker.yaml
ecobee: !include components/ecobee.yaml
group: !include_dir_merge_named ui/groups/
influxdb: !include components/influxdb.yaml
input_number: !include components/input_number.yaml
input_select: !include components/input_select.yaml
intent_script: !include_dir_merge_named components/intents
isy994: !include components/isy994.yaml
light: !include components/lights.yaml
lock: !include components/locks.yaml
media_player: !include components/media_players.yaml
mqtt: !include components/mqtt.yaml
notify: !include components/notify.yaml
script: !include components/scripts.yaml
sensor: !include components/sensors.yaml
shell_command: !include_dir_merge_named components/shell_commands/
switch: !include components/switches.yaml
telegram_bot: !include components/telegram_bot.yaml
tts: !include components/tts.yaml
weather: !include components/weather.yaml
