homeassistant:
  # Name of the location where Home Assistant is running
  name: Dunn's Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_location
  longitude: !secret longitude_location
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 192
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include ui/customize.yaml
  # Trusted Networks
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.8.0.0/16
        - !secret my_ip
    - type: homeassistant

# Zones
zone:
  - name: Home
    latitude: !secret latitude_location
    longitude: !secret longitude_location
    radius: 500
    icon: mdi:home
  - name: Work
    latitude: !secret her_work_latitude_location
    longitude: !secret her_work_longitude_location
    radius: 200
    icon: mdi:hospital-marker


# Enables the frontend
frontend:
  themes: !include_dir_merge_named ui/themes/

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.26
    - 192.168.1.41
    - 192.168.1.204
    - 192.168.1.228
  ip_ban_enabled: false
  login_attempts_threshold: 3


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv
    - yamaha

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Support Android/ iOS mobile apps
mobile_app:

# Logging
logger:
  default: error
  logs:
    homeassistant.components.myq: critical

# Enables a map showing the location of tracked devices
map:

recorder:
  db_url: !secret db_url

# System health for APIs
system_health:

# Track the sun
sun:

# Components
automation: !include_dir_list automations/
binary_sensor: !include components/binary_sensors.yaml
camera: !include components/camera.yaml
climate: !include components/climate.yaml
cloud: !include components/cloud.yaml
cover: !include components/cover.yaml
ecobee: !include components/ecobee.yaml
group: !include_dir_merge_named ui/groups/
ifttt: !include components/ifttt.yaml
image_processing: !include components/image_processing.yaml
influxdb: !include components/influxdb.yaml
input_number: !include components/input_number.yaml
input_select: !include components/input_select.yaml
# intent_script: !include_dir_merge_named components/intents
isy994: !include components/isy994.yaml
light: !include components/lights.yaml
media_player: !include components/media_players.yaml
mqtt: !include components/mqtt.yaml
notify: !include components/notify.yaml
nzbget: !include components/nzbget.yaml
script: !include scripts.yaml
sensor: !include components/sensors.yaml
speedtestdotnet:
  monitored_conditions:
    - download
    - ping
    - upload
stream:
switch: !include components/switches.yaml
# telegram_bot: !include components/telegram_bot.yaml
tts: !include components/tts.yaml
unifi: !include components/unifi.yaml
weather: !include components/weather.yaml