##################
# BINARY SENSORS #
##################

- platform: hikvision
  name: driveway camera sensor
  host: 10.10.2.6
  username: !secret driveway_username
  password: !secret driveway_password

- platform: hikvision
  name: backyard camera sensor
  host: 10.10.2.7
  username: !secret backyard_username
  password: !secret backyard_password

- platform: hikvision
  name: backyard west camera sensor
  host: 10.10.2.8
  username: !secret backyard_west_username
  password: !secret backyard_west_password

  # Kitchen combined Ring sensor & Ecobee sensor
- platform: template
  sensors:
    kitchen_dual_occupancy:
      friendly_name: Kitchen
      device_class: motion
      value_template: "{{ is_state('binary_sensor.kitchen_occupancy', 'on') or is_state('binary_sensor.kitchen_motion', 'on') }}"

# Living room combined Ring sensor & Ecobee sensor
- platform: template
  sensors:
    living_room_dual_occupancy:
      friendly_name: Living
      device_class: motion
      value_template: "{{ is_state('binary_sensor.living_room_occupancy', 'on') or is_state('binary_sensor.living_motion', 'on') }}"