##########
# CAMERA #
##########

# Dog Crate
- platform: generic
  name: Dog Crate Stream
  still_image_url: !secret dog_jpeg
  stream_source: !secret dog_rtsp

# Driveway
- platform: generic
  name: Driveway Stream
  username: !secret driveway_username
  password: !secret driveway_password
  authentication: digest
  still_image_url: !secret driveway_jpeg
  stream_source: !secret driveway_rtsp

- platform: generic
  name: Driveway Low Stream
  username: !secret driveway_username
  password: !secret driveway_password
  authentication: digest
  still_image_url: !secret driveway_jpeg
  stream_source: !secret driveway_low_rtsp

- platform: proxy
  name: Driveway Proxy
  entity_id: camera.driveway_stream
  max_stream_width: 1280

- platform: local_file
  name: Latest Persons Detection
  file_path: /config/www/driveway_stream_latest.jpg

- platform: local_file
  name: Latest Vehicles Detection
  file_path: /config/www/driveway_stream_vehicles_latest.jpg

# Backyard
- platform: generic
  name: Backyard Stream
  username: !secret backyard_username
  password: !secret backyard_password
  authentication: digest
  still_image_url: !secret backyard_jpeg
  stream_source: !secret backyard_rtsp

- platform: proxy
  name: Backyard Proxy
  entity_id: camera.backyard_stream
  max_stream_width: 1280

- platform: local_file
  name: Latest Animals Detection
  file_path: /config/www/backyard_stream_latest.jpg
