##########
# CAMERA #
##########

# Driveway
- platform: generic
  name: Driveway Stream
  username: !secret driveway_username
  password: !secret driveway_password
  authentication: digest
  still_image_url: !secret driveway_jpeg
  stream_source: !secret driveway_rtsp

- platform: generic
  name: Driveway Low Stream
  username: !secret driveway_username
  password: !secret driveway_password
  authentication: digest
  still_image_url: !secret driveway_jpeg
  stream_source: !secret driveway_low_rtsp

# - platform: proxy
#   name: Driveway Proxy
#   entity_id: camera.driveway_stream
#   max_stream_width: 1280

- platform: local_file
  name: Latest Persons Detection
  file_path: /config/www/driveway_stream_latest.jpg
   
- platform: mjpeg
  mjpeg_url: !secret driveway_mjpeg
  name: Driveway Camera
  username: !secret bi_username
  password: !secret bi_password
  authentication: basic

# Backyard East
- platform: generic
  name: Backyard Stream
  username: !secret backyard_username
  password: !secret backyard_password
  authentication: digest
  still_image_url: !secret backyard_jpeg
  stream_source: !secret backyard_rtsp

# - platform: proxy
#   name: Backyard Proxy
#   entity_id: camera.backyard_stream
#   max_stream_width: 1280

- platform: local_file
  name: Latest Animal(s) Detection
  file_path: /config/www/backyard_stream_animal_latest.jpg

- platform: local_file
  name: Latest Person(s) Backyard
  file_path: /config/www/backyard_stream_latest.jpg

- platform: mjpeg
  mjpeg_url: !secret backyard_east_mjpeg
  name: Backyard East Camera
  username: !secret bi_username
  password: !secret bi_password
  authentication: basic

# Backyard West
- platform: generic
  name: Backyard West Stream
  username: !secret backyard_west_username
  password: !secret backyard_west_password
  authentication: digest
  still_image_url: !secret backyard_west_jpeg
  stream_source: !secret backyard_west_rtsp

# - platform: proxy
#   name: Backyard West Proxy
#   entity_id: camera.backyard_west_stream
#   max_stream_width: 1280
  
- platform: local_file
  name: Last Person(s) Backyard Entrances
  file_path: /config/www/backyard_west_stream_latest.jpg

- platform: mjpeg
  mjpeg_url: !secret backyard_west_mjpeg
  name: Backyard West Camera
  username: !secret bi_username
  password: !secret bi_password
  authentication: basic