##########
# CAMERA #
##########

- platform: uvc
  nvr: 192.168.1.21
  key: !secret unifi_key
  password: !secret uvc_password

- platform: generic
  name: Driveway Stream
  username: !secret driveway_username
  password: !secret driveway_password
  still_image_url: !secret driveway_jpeg
  stream_source: !secret driveway_rtsp

# - platform: mjpeg
#   name: Driveway Camera
#   mjpeg_url: !secret drive_way_mjpeg
#
# - platform: mjpeg
#   name: Kennel Camera
#   mjpeg_url: !secret kennel_mjpeg
