
# Driveway Smarts
# - platform: tensorflow
#   source:
#     - entity_id: camera.driveway_stream
#       name: driveway_camera_person
#   file_out:
#     - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
#     - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_persons_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#   scan_interval: 604800
#   model:
#     graph: "/config/tensorflow/model/frozen_inference_graph.pb"
#     categories:
#       - category: person
#         area:
#           right: 0.9
#           left: 0.02

# - platform: tensorflow
#   source:
#     - entity_id: camera.driveway_stream
#       name: driveway_camera_vehicles
#   file_out:
#     - "/config/www/{{ camera_entity.split('.')[1] }}_vehicles_latest.jpg"
#     - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_vehicle_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#   scan_interval: 604800
#   model:
#     graph: "/config/tensorflow/model/frozen_inference_graph.pb"
#     categories:
#       - category: car
#         area:
#           left: 0.2
#           right: 0.9
#           top: 0.1
#       - category: truck
#         area:
#           left: 0.2
#           right: 0.9
#           top: 0.1

# - platform: tensorflow
#   source:
#     - entity_id: camera.driveway_stream
#       name: driveway_camera_smarts
#   file_out:
#     - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
#     - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#   scan_interval: 604800
#   model:
#     graph: /config/tensorflow/models/efficientdet_d0_coco17_tpu-32/
#     categories:
#       - category: car
#         area:
#           left: 0.2
#           right: 0.9
#           top: 0.1
#       - category: truck
#         area:
#           left: 0.2
#           right: 0.9
#           top: 0.1
#       - category: person
#         area:
#           right: 0.8
#           left: 0.02

# Backyard East Smarts
# - platform: tensorflow
#   source:
#     - entity_id: camera.backyard_stream
#       name: backyard_camera_animals
#   file_out:
#     - "/config/www/{{ camera_entity.split('.')[1] }}_animal_latest.jpg"
#     - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_animal_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#   scan_interval: 604800
#   model:
#     graph: /config/tensorflow/models/efficientdet_d0_coco17_tpu-32/
#     labels: "tensorflow/object_detection/data/oid_bbox_trainable_label_map.pbtxt"
#     categories:
#       - category: Deer
#         area:
#           top: 0.01
#       - category: Animal
#         area:
#           top: 0.01

# - platform: tensorflow
#   source:
#     - entity_id: camera.backyard_stream
#       name: backyard_east_camera_smarts
#   file_out:
#     - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
#     - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#   scan_interval: 604800
#   model:
#     graph: /config/tensorflow/models/efficientdet_d0_coco17_tpu-32/
#     categories:
#       - category: person
#         area:
#           top: 0.01
#       - category: dog
#         area:
#           top: 0.01
#       - category: cat
#         area:
#           top: 0.01

# # Backyard West Smarts
# - platform: tensorflow
#   source:
#     - entity_id: camera.backyard_west_stream
#       name: backyard_west_camera_smarts
#   file_out:
#     - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
#     - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#   scan_interval: 604800
#   model:
#     graph: /config/tensorflow/models/efficientdet_d0_coco17_tpu-32/
#     categories:
#       - category: person
#       - category: dog
#       - category: cat

- platform: doods
  scan_interval: 3600
  url: http://doods.du.nn
  detector: tensorflow
  source:
    - entity_id: camera.driveway_stream
    - entity_id: camera.backyard_west_stream
    - entity_id: camera.backyard_east_stream
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/tensorflow/images/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  confidence: 87
  area:
    covers: false
  labels:
    - person
    - car
    - truck
    - dog
    - cat
