
# Driveway Smarts
- platform: tensorflow
  source:
    - entity_id: camera.driveway_stream
      name: driveway_camera_person
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_persons_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: person
        area:
          right: 0.9
          left: 0.02

- platform: tensorflow
  source:
    - entity_id: camera.driveway_stream
      name: driveway_camera_vehicles
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_vehicles_latest.jpg"
    - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_vehicle_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: car
        area:
          left: 0.2
          right: 0.9
      - category: truck
        area:
          left: 0.2
          right: 0.9

- platform: tensorflow
  source:
    - entity_id: camera.driveway_stream
      name: driveway_camera_smarts
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: car
        area:
          left: 0.2
          right: 0.9
      - category: truck
        area:
          left: 0.2
          right: 0.9
      - category: person
        area:
          right: 0.9
          left: 0.02

# Backyard East Smarts
- platform: tensorflow
  source:
    - entity_id: camera.backyard_stream
      name: backyard_camera_animals
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_animal_latest.jpg"
    - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_animal_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    labels: "tensorflow/object_detection/data/oid_bbox_trainable_label_map.pbtxt"
    categories:
      - category: Deer
        area:
          top: 0.01
      - category: Animal
        area:
          top: 0.01

- platform: tensorflow
  source:
    - entity_id: camera.backyard_stream
      name: backyard_camera_person
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_person_latest.jpg"
    - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_person_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: person
        area:
          top: 0.01
      - category: Dog
        area:
          top: 0.01
      - category: Cat
        area:
          top: 0.01

# Backyard West Smarts
- platform: tensorflow
  source:
    - entity_id: camera.backyard_west_stream
      name: backyard_west_camera_smarts
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: person
      - category: dog
      - category: cat
