
# Driveway Smarts
- platform: tensorflow
  source:
    - entity_id: camera.driveway_stream
      name: driveway_camera_person
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_persons_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: person
        area:
          right: 0.82
          top: 0.15

- platform: tensorflow
  source:
    - entity_id: camera.driveway_stream
      name: driveway_camera_vehicles
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_vehicles_latest.jpg"
    - "/config/tensorflow/images/driveway/{{ camera_entity.split('.')[1] }}_vehicle_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - category: car
        area:
          top: 0.2
      - category: truck
        area:
          top: 0.2

# Backyard Smarts
- platform: tensorflow
  source:
    - entity_id: camera.backyard_stream
      name: backyard_camera_animals
  file_out:
    - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/tensorflow/images/backyard/{{ camera_entity.split('.')[1] }}_animal_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: "/config/tensorflow/model/frozen_inference_graph.pb"
    categories:
      - dog
      - cat
      - animal
