##########
# LIGHTS #
##########

- platform: switch
  name: living room ceiling lights
  entity_id: switch.living_room_dome_lights

- platform: switch
  name: living room fan light
  entity_id: switch.living_room_light
