##########
# LIGHTS #
##########

- platform: switch
  name: dining room light
  entity_id: switch.dining_room_light

- platform: switch
  name: east hallway light
  entity_id: switch.east_hallway_light

- platform: switch
  name: entry light
  entity_id: switch.entry_light

- platform: switch
  name: kitchen cabinet lights
  entity_id: switch.cabinet_lights

- platform: switch
  name: kitchen ceiling lights
  entity_id: switch.kitchen_light

- platform: switch
  name: living room ceiling lights
  entity_id: switch.living_room_dome_lights

- platform: switch
  name: living room fan light
  entity_id: switch.living_room_light

- platform: switch
  name: office floor lamp
  entity_id: switch.office_floor_lamp

- platform: switch
  name: patio light
  entity_id: switch.patio_light

- platform: switch
  name: porch lights
  entity_id: switch.porch_lights

- platform: switch
  name: west hallway light
  entity_id: switch.west_hallway_light
