###########
# SENSORS #
###########

- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - temperature
    - humidity
    - wind_speed
    - wind_gust
  hourly_forecast:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12

- platform: rtorrent
  url: http://192.168.1.101:8008/RPC2
  monitored_variables:
    - current_status
    - download_speed
    - upload_speed

# Garage Temperature Avg
- platform: min_max
  name: Garage Temperature
  type: mean
  entity_ids:
    - sensor.garage_east_wall_conditions_temperature
    - sensor.garage_north_wall_conditions_temperature

# Garage Humidity Avg
- platform: min_max
  name: Garage Humidity
  type: mean
  entity_ids:
    - sensor.garage_east_wall_conditions_relative_humidity
    - sensor.garage_north_wall_conditions_relative_humidity
