###########
# SENSORS #
###########

- platform: template
  sensors:
    compute_power:
      friendly_name: "Compute Power"
      entity_id: "switch.server_rack_switch"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.server_rack_switch', 'current_power_w') | round(0) }}"

- platform: statistics
  entity_id: sensor.compute_power
  name: Compute Stats
  max_age:
    days: 30

- platform: template
  sensors:
    compute_power_cost:
      friendly_name: "Compute Cost"
      entity_id: "sensor.compute_stats_mean"
      unit_of_measurement: "USD"
      value_template: "{{ (states.sensor.compute_stats_mean.attributes['mean'] | float * 0.72 * 0.07772) | round(2) }}"

- platform: template
  sensors:
    networking_power:
      friendly_name: "Networking Power"
      entity_id: "switch.network_rack_switch"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.network_rack_switch', 'current_power_w') | round(0) }}"

- platform: statistics
  entity_id: sensor.networking_power
  name: Networking Stats
  max_age:
    days: 30

- platform: template
  sensors:
    networking_power_cost:
      friendly_name: "Networking Cost"
      entity_id: "sensor.networking_stats_mean"
      unit_of_measurement: "USD"
      value_template: "{{ (states.sensor.networking_stats_mean.attributes['mean'] | float * 0.72 * 0.07772) | round(2) }}"

- platform: template
  sensors:
    media_rack_power:
      friendly_name: "Media Rack Power"
      entity_id: "sensor.media_rack_power_draw"
      unit_of_measurement: "W"
      value_template: "{{ states('sensor.media_rack_power_draw') | round(0) }}"

- platform: statistics
  entity_id: sensor.media_rack_power
  name: Media Rack Stats
  max_age:
    days: 30

- platform: template
  sensors:
    media_rack_power_cost:
      friendly_name: "Media Rack Cost"
      entity_id: "sensor.media_rack_stats_mean"
      unit_of_measurement: "USD"
      value_template: "{{ (states.sensor.media_rack_stats_mean.attributes['mean'] | float * 0.72 * 0.07772) | round(2) }}"

- platform: mqtt
  state_topic: "smartthings/Front Door/battery"
  name: "Lock Battery"
  qos: 0
  unit_of_measurement: "%"

- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - temperature
    - humidity
    - wind_speed
    - wind_gust
  hourly_forecast:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12

- platform: rtorrent
  url: http://192.168.1.101:8008/RPC2
  monitored_variables:
    - current_status
    - download_speed
    - upload_speed

- platform: template
  sensors:
    total_download:
      friendly_name: "Total Download"
      entity_id:
        - sensor.rtorrent_down_speed
        - sensor.nzbget_speed
      unit_of_measurement: "kB/s"
      value_template: "{{ states('sensor.rtorrent_down_speed')|float + (states('sensor.nzbget_speed')|float * 1000) | round(2) }}"
