alias: Living Room Soundbar Volume Control (Media to Slider)
trigger:
  - platform: state
    entity_id: media_player.soundbar
action:
   service: input_number.set_value
   data_template:
     entity_id: input_number.living_room_soundbar_volume_slider
     value: >
        {{ ( ( trigger.to_state.attributes.volume_level | float ) * 100.0 ) | round(0) }}

alias: Living Room Soundbar Volume Control (Slider to Media)
trigger:
  - platform: state
    entity_id: input_number.living_room_soundbar_volume_slider
action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.soundbar
      volume_level: >
        {{ (trigger.to_state.state | float / 100.0) | round(2) }}
