alias: Living Room Soundbar Volume Control (Media to Slider)
trigger:
  - platform: state
    entity_id: media_player.soundbar
action:
   service: input_number.set_value
   data_template:
     entity_id: input_number.living_room_soundbar_volume_slider
     value: >
        {{ ( ( trigger.to_state.attributes.volume_level | float ) * 100.0 ) | round(0) }}
