alias: Master Bedroom Home Volume Control (Media to Slider)
id: master_bedroom_home_volume_control_media_to_slider
trigger:
  - platform: state
    entity_id: media_player.master_bedroom_home
action:
   service: input_number.set_value
   data_template:
     entity_id: input_number.master_bedroom_home_volume_slider
     value: >
        {{ ( ( trigger.to_state.attributes.volume_level | float ) * 100.0 ) | round(0) }}
